# Generated by Django 2.2.7 on 2019-12-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='file',
        ),
    ]
